version: '3'
services:
  postgresql:
    image: postgres
    container_name: nest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DATABASE=nest
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nest
    ports:
      - "6379:6379"